# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "fbd7722d4d4315e73763b9f806357569cf2c744cb3cf017961683d0ee485bbb4"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4708db0439d6cd54942350cad6afb43f4cd74a7c4db3b07167ecb45afea8cc3"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26b5eb443c24122a10adfb562378f4f24f258c099d0b376970d592cb42351d0b"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d8e5efeebc2489b12eebf538effd46093c432c401da465d6c16dc2cf9c4aa12"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "courier"
  desc "courier syncs Openlane organization controls and policies with a git repository"
  homepage "https://github.com/theopenlane/courier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  # No zap stanza required

end
