# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "44f9562c3060ad803bc5a27bdb4df37413ecb7b7f6f04ecf6dcb434b00a880cc"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b78506c96df8a33c9ccdfb86a6a9e7a7b73457c4a112ff75691715e32f4d6f1d"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc8cf0ede025e503ae2df0e59e592bfb0c188e65ebee7b6c1e45a866a43fb851"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bdd116101a9d571cb49ab0bbaac573140fe158f6da28fc367edb5cc30bf71ea"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "courier"
  desc "courier syncs Openlane organization controls and policies with a git repository"
  homepage "https://github.com/theopenlane/courier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  # No zap stanza required

end
