# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "8cc317d905e5c88b80864d4471171b722f42c61fe0d212bcf33968627618fdd2"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f71120f3b2ed960c9dff629e3b88988845fc8f1a375911308a9cac32762be30"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4cf747996a87904c2ac3e93405fc5170276cf2edb9dd2d3fd9c78b482fc645c"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a74d4e899df619cfd08bd1883dd7cd3fd6812ddd585bbe4fcda5a4b6be346938"
      url "https://github.com/theopenlane/courier/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "courier"
  desc "courier syncs Openlane organization controls and policies with a git repository"
  homepage "https://github.com/theopenlane/courier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  # No zap stanza required

end
