# This file was generated by GoReleaser. DO NOT EDIT.
cask "openlane" do
  desc "openlane is the client CLI for interacting with the openlane server"
  homepage "https://github.com/theopenlane/core"
  version "0.30.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openlane"

  on_macos do
    on_intel do
      url "https://github.com/theopenlane/core/releases/download/v0.30.0/openlane_0.30.0_darwin_amd64.tar.gz"
      sha256 "c97a7774e9d86bb28ef0ab930e11736dec90698913ddc567465e21a263ee55ce"
    end
    on_arm do
      url "https://github.com/theopenlane/core/releases/download/v0.30.0/openlane_0.30.0_darwin_arm64.tar.gz"
      sha256 "a3ed0629a47356c74e88017695bf4f389d47b591cee9271f24f96ee3ee1862f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/theopenlane/core/releases/download/v0.30.0/openlane_0.30.0_linux_amd64.tar.gz"
      sha256 "a68d1427a4ae8c94f89fac3cf3a3872e7603c43e4b9466d6cbd1219ffa15231e"
    end
    on_arm do
      url "https://github.com/theopenlane/core/releases/download/v0.30.0/openlane_0.30.0_linux_arm64.tar.gz"
      sha256 "fa8cbd679456a67141b7e9d6513a02e5dedb0afdb8ddc6bb4c0b3e635fc1de22"
    end
  end

  # No zap stanza required
end
