# This file was generated by GoReleaser. DO NOT EDIT.
cask "openlane" do
  version "1.32.0"

  on_macos do
    on_intel do
      sha256 "4a8c755a72018608e7d160187723cdb6b3a0661b1da511392180e7344e100bff"
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "566bf9ebb88ccae69ca758fe7d2c1e93b60f94e2cebc47c01af9eaaf6887a66d"
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82815cc02142f150f4ddc8c88df91826d5c441326cee261536e2024cd333704c"
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff2d7795e7552238e8d6a24aa56d3c3ded9003e6ae29977ae0093b492445726c"
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openlane"
  desc "openlane is the client CLI for interacting with the openlane server"
  homepage "https://github.com/theopenlane/core"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openlane"

  # No zap stanza required

end
