# This file was generated by GoReleaser. DO NOT EDIT.
cask "openlane" do
  name "openlane"
  desc "openlane is the client CLI for interacting with the openlane server"
  homepage "https://github.com/theopenlane/core"
  version "0.32.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openlane"

  on_macos do
    on_intel do
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_darwin_amd64.tar.gz"
      sha256 "dbb687c01f212e6ef55912cd55d7eccfb20951ad64c79f0ad2e3cbdde4561f1c"
    end
    on_arm do
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_darwin_arm64.tar.gz"
      sha256 "25c3d2e0c55394790c11819d19950287dd6e211d64eb4e5a4ecfc3dafc0cf857"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_linux_amd64.tar.gz"
      sha256 "6f24622fa3937cc6febda39a0b39dba7d2fe556834da741be621e505e26d0ce1"
    end
    on_arm do
      url "https://github.com/theopenlane/core/releases/download/v#{version}/openlane_#{version}_linux_arm64.tar.gz"
      sha256 "d72de27ab44eb9c26fbd7f6cb34bc5c7704147fdb9338d403c0459e6f65fa3cd"
    end
  end

  # No zap stanza required
end
