# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openlane < Formula
  desc "openlane is the client CLI for interacting with the openlane server"
  homepage "https://github.com/theopenlane/core"
  version "0.22.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theopenlane/core/releases/download/v0.22.3/openlane_0.22.3_darwin_amd64.tar.gz"
      sha256 "613104e88e947c8338386161b33dee2409b70fd7679962eceba2254e4b24e270"

      def install
        bin.install "openlane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theopenlane/core/releases/download/v0.22.3/openlane_0.22.3_darwin_arm64.tar.gz"
      sha256 "04b65b5bb29516f74bca48f46cc7397ffe5187f29b092f4e5d96918d2e1e5975"

      def install
        bin.install "openlane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/theopenlane/core/releases/download/v0.22.3/openlane_0.22.3_linux_amd64.tar.gz"
      sha256 "194b8c35dac0619c910cf44f95bc93eda858974469efe7bef62939cee9db9e32"
      def install
        bin.install "openlane"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/theopenlane/core/releases/download/v0.22.3/openlane_0.22.3_linux_arm64.tar.gz"
      sha256 "a5245217db3d3388085d2f9f5b14a55a0cd50b6a5fde9e8fd8030f594f71c090"
      def install
        bin.install "openlane"
      end
    end
  end

  test do
    system "#{bin}/openlane --help"
  end
end
