# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openlane < Formula
  desc "openlane is the client CLI for interacting with the openlane server"
  homepage "https://github.com/theopenlane/core"
  version "0.17.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theopenlane/core/releases/download/v0.17.2/openlane_0.17.2_darwin_amd64.tar.gz"
      sha256 "4fc5bbae3a93b8153f62b3c832117abc0656196f150d8ecd286332479abbb6ad"

      def install
        bin.install "openlane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theopenlane/core/releases/download/v0.17.2/openlane_0.17.2_darwin_arm64.tar.gz"
      sha256 "4f969b0cb6c0da633872fe2ba8d9b184bc597d3bd0a84b70b5828c952b27f60e"

      def install
        bin.install "openlane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/theopenlane/core/releases/download/v0.17.2/openlane_0.17.2_linux_amd64.tar.gz"
      sha256 "27ae7ca2799ecd250941d2132faea96392be111328e357a169b03390b6dc0b95"
      def install
        bin.install "openlane"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/theopenlane/core/releases/download/v0.17.2/openlane_0.17.2_linux_arm64.tar.gz"
      sha256 "a929cba6682ab39160fb40214bcf17b71daccd11371531d844049a6abb5c7a38"
      def install
        bin.install "openlane"
      end
    end
  end

  test do
    system "#{bin}/openlane --help"
  end
end
